### ISSUE TITLE
require(wp-content/plugins/wp2static-addon-advanced-detection-master/vendor/autoload.php): failed to open stream:

### ISSUE THREAD

**Issue by twardoch** [leonstafford/wp2static-addon-advanced-detection#2]
With wp2static 7.1.6, when activating this addon, I get: 

Warning: require(wp-content/plugins/wp2static-addon-advanced-detection-master/vendor/autoload.php): failed to open stream: No such file or directory in wp-content/plugins/wp2static-addon-advanced-detection-master/wp2static-addon-advanced-detection.php on line 23

Fatal error: require(): Failed opening required 'wp-content/plugins/wp2static-addon-advanced-detection-master/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in wp-content/plugins/wp2static-addon-advanced-detection-master/wp2static-addon-advanced-detection.php on line 23

**Comment by leonstafford** [comment]
Hi @twardoch, these GitHub repos require running composer install to use.

For easily installable zips, you can grab from https://wp2static.com/thanks-for-supporting

**Comment by twardoch** [comment]
Thank you, I realized that after all. This add-on seems not to work with wp2s 7.1.6 though (instslls but no options appear).
